### ISSUE TITLE
Periodically receive "Duplicate transaction" error when creating two transfers in a row

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/ledger#30]
When I run test cases which perform two transfers in a row, the second one sometimes fails with this error:

```
Error: the string "{\"code\":409,\"message\":\"Conflict\",\"error\":{\"code\":3040008,\"name\":\"tx_duplicate\",\"what\":\"Duplicate transaction\",\"details\":[{\"message\":\"duplicate transaction 2ee5a0501591661ac01b9ef5ae6a6254d03579c229b6a3635065830eda191879\",\"file\":\"producer_plugin.cpp\",\"line_number\":361,\"method\":\"on_incoming_transaction_async\"}]}}" wasthrown, throw an Error :)
```

You should be able to reproduce this by running `npm run test` in the ledger-js repository.

Here's the info when I turn on verbose:

```
api > post       http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_abi {"account_name":"vtxledger"}
api < response   http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_abi {"account_name":"vtxledger","abi":{"version":"eosio::abi/1.0","types":[],"structs":[{"name":"entry","base":"","fields":[{"name":"s","type":"name"},{"name":"key","type":"uint64"},{"name":"Id","type":"uint64"},{"name":"sToKey","type":"string"},{"name":"fromAccount","type":"string"},{"name":"toAccount","type":"string"},{"name":"toKey","type":"uint64"},{"name":"fromKey","type":"string"},{"name":"amount","type":"uint64"}]},{"name":"getblnc","base":"","fields":[{"name":"account","type":"string"},{"name":"tokey","type":"string"}]},{"name":"retrvtxns","base":"","fields":[{"name":"account","type":"string"},{"name":"tokey","type":"string"},{"name":"limit","type":"uint64"}]},{"name":"rcrdtfr","base":"","fields":[{"name":"s","type":"name"},{"name":"fromaccount","type":"string"},{"name":"toaccount","type":"string"},{"name":"fromkey","type":"string"},{"name":"tokey","type":"string"},{"name":"amount","type":"uint64"}]}],"actions":[{"name":"getblnc","type":"getblnc","ricardian_contract":""},{"name":"retrvtxns","type":"retrvtxns","ricardian_contract":""},{"name":"rcrdtfr","type":"rcrdtfr","ricardian_contract":""}],"tables":[{"name":"entry","index_type":"i64","key_names":["s"],"key_types":["name"],"type":"entry"}],"ricardian_clauses":[],"error_messages":[],"abi_extensions":[]}}
api > post       http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_abi {"account_name":"vtxledger"}
api < response   http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_abi {"account_name":"vtxledger","abi":{"version":"eosio::abi/1.0","types":[],"structs":[{"name":"entry","base":"","fields":[{"name":"s","type":"name"},{"name":"key","type":"uint64"},{"name":"Id","type":"uint64"},{"name":"sToKey","type":"string"},{"name":"fromAccount","type":"string"},{"name":"toAccount","type":"string"},{"name":"toKey","type":"uint64"},{"name":"fromKey","type":"string"},{"name":"amount","type":"uint64"}]},{"name":"getblnc","base":"","fields":[{"name":"account","type":"string"},{"name":"tokey","type":"string"}]},{"name":"retrvtxns","base":"","fields":[{"name":"account","type":"string"},{"name":"tokey","type":"string"},{"name":"limit","type":"uint64"}]},{"name":"rcrdtfr","base":"","fields":[{"name":"s","type":"name"},{"name":"fromaccount","type":"string"},{"name":"toaccount","type":"string"},{"name":"fromkey","type":"string"},{"name":"tokey","type":"string"},{"name":"amount","type":"uint64"}]}],"actions":[{"name":"getblnc","type":"getblnc","ricardian_contract":""},{"name":"retrvtxns","type":"retrvtxns","ricardian_contract":""},{"name":"rcrdtfr","type":"rcrdtfr","ricardian_contract":""}],"tables":[{"name":"entry","index_type":"i64","key_names":["s"],"key_types":["name"],"type":"entry"}],"ricardian_clauses":[],"error_messages":[],"abi_extensions":[]}}
api > post       http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_info {}
api < response   http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_info {"server_version":"e87d245d","chain_id":"cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f","head_block_num":5989,"last_irreversible_block_num":5988,"last_irreversible_block_id":"000017640820bdd89c82eec5a68eec76e9c99d23961f7b16ef7993112ff67ff6","head_block_id":"00001765acec5b4731bb9ca9d99c7c64c0d5e18a466b0631d122b864a10e34a9","head_block_time":"2018-09-10T14:53:58.000","head_block_producer":"eosio","virtual_block_cpu_limit":79762133,"virtual_block_net_limit":419036441,"block_cpu_limit":197948,"block_net_limit":1048336,"server_version_string":"v1.2.3"}
api > post       http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_block {"block_num_or_id":5988}
api < response   http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/get_block {"timestamp":"2018-09-10T14:53:57.500","producer":"eosio","confirmed":0,"previous":"00001763397dd10bc755a8b3e91f8cec90826e4756a612af2d2b1770bd8e37b2","transaction_mroot":"0000000000000000000000000000000000000000000000000000000000000000","action_mroot":"c01e3845198bbdf5a97025cd080b197ae3f4bc60da0114a8b8a807f080f5922f","schedule_version":0,"new_producers":null,"header_extensions":[],"producer_signature":"SIG_K1_K3ZSkHagXiteuxf6HtsjX6g7t6uK3WxoTEmQua5zF4LQgUf9epmnMSNHwU1vjRFDa2wgZTWrnqf2eGs1PVx9r3uq56jMkH","transactions":[],"block_extensions":[],"id":"000017640820bdd89c82eec5a68eec76e9c99d23961f7b16ef7993112ff67ff6","block_num":5988,"ref_block_prefix":3320742556}
api > post       http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-09-10T14:54:58","ref_block_num":5988,"ref_block_prefix":3320742556,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"vtxledger","name":"rcrdtfr","authorization":[{"actor":"vtxledger","permission":"active"}],"data":"00fcd5d8a89b7bde08767478747275737408767478747275737435454f5335764271693859537a4643655476347765525477427a566b47435935504e35486d314770333133336d3867394d744854625735454f533853474d4a3958726863364a4a565655347261546b396b41583869766b575972436235707a626b4245634b344675427558366400000000000000"}],"transaction_extensions":[]},"signatures":["SIG_K1_K7svjTHmXZZNiGS89oabuSWc6kJNQuH244WGwuGDJ2SSVmsGiuAcXkUa33Tmrf4Evc5hH4Dzi3b2oevUKQrUVH8QS6zvb3"]}
api < error      { message: 'duplicate transaction ec28a3297061c80a197926ed3f9e6c19b2371e2e6e830faed9dedaea5a394926',
  file: 'producer_plugin.cpp',
  line_number: 361,
  method: 'on_incoming_transaction_async' } http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-09-10T14:54:58","ref_block_num":5988,"ref_block_prefix":3320742556,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"vtxledger","name":"rcrdtfr","authorization":[{"actor":"vtxledger","permission":"active"}],"data":"00fcd5d8a89b7bde08767478747275737408767478747275737435454f5335764271693859537a4643655476347765525477427a566b47435935504e35486d314770333133336d3867394d744854625735454f533853474d4a3958726863364a4a565655347261546b396b41583869766b575972436235707a626b4245634b344675427558366400000000000000"}],"transaction_extensions":[]},"signatures":["SIG_K1_K7svjTHmXZZNiGS89oabuSWc6kJNQuH244WGwuGDJ2SSVmsGiuAcXkUa33Tmrf4Evc5hH4Dzi3b2oevUKQrUVH8QS6zvb3"]}
{ Error: {"code":409,"message":"Conflict","error":{"code":3040008,"name":"tx_duplicate","what":"Duplicate transaction","details":[{"message":"duplicate transaction ec28a3297061c80a197926ed3f9e6c19b2371e2e6e830faed9dedaea5a394926","file":"producer_plugin.cpp","line_number":361,"method":"on_incoming_transaction_async"}]}}
    at /Users/shawn/Development/github/ledger-js/node_modules/eosjs-api/lib/apigen.js:112:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 409, statusText: 'Conflict' }
[push_transaction error] '{"code":409,"message":"Conflict","error":{"code":3040008,"name":"tx_duplicate","what":"Duplicate transaction","details":[{"message":"duplicate transaction ec28a3297061c80a197926ed3f9e6c19b2371e2e6e830faed9dedaea5a394926","file":"producer_plugin.cpp","line_number":361,"method":"on_incoming_transaction_async"}]}}', transaction 'c285965b64179c82eec500000000010000b88a25157bde000000e0ae9c2eba010000b88a25157bde00000000a8ed32328e0100fcd5d8a89b7bde08767478747275737408767478747275737435454f5335764271693859537a4643655476347765525477427a566b47435935504e35486d314770333133336d3867394d744854625735454f533853474d4a3958726863364a4a565655347261546b396b41583869766b575972436235707a626b4245634b34467542755836640000000000000000'
{"code":409,"message":"Conflict","error":{"code":3040008,"name":"tx_duplicate","what":"Duplicate transaction","details":[{"message":"duplicate transaction ec28a3297061c80a197926ed3f9e6c19b2371e2e6e830faed9dedaea5a394926","file":"producer_plugin.cpp","line_number":361,"method":"on_incoming_transaction_async"}]}}
undefined
```

**Comment by sylvaincormier** [comment]
This isn't a bug per-say, you can resend the transaction after the expiration of the original.

You can update the TAPOS every 3 seconds (or use older tapos)
You can update the expiration if you really need to
You can add a dummy message to the transaction as well.

**Comment by shawnlauzon** [comment]
I don't understand what you mean when you say it's not a bug. The error returned is "duplicate transaction", but from the client perspective, there was no duplicate: the client was attempting to perform 2 independent operations.

Something definitely needs to be fixed, but maybe there is some change needed on the LedgerJs side. Please provide more information on what can be done to prevent this error from occurring.

**Comment by shawnlauzon** [comment]
After further discussion, sounds like a possible workaround for this for now is for some code to pass some unique data in each call.

If I pass a new parameter `nonce` which is a String UUID to each of the contracts, do you think that would resolve the problem?

**Comment by sylvaincormier** [comment]
Transactions submitted even with 1 second interval should be unique since they reference different head blocks (even if all other fields in the transactions are exactly the same). 
Another option is to use the -f option in cleos by including a nonce action in the transaction that will make the tx unique.
-f,--force-unique force the transaction to be unique. This will consume extra bandwidth.
Passing a different nonce with each tx will resolve the problem.

**Comment by shawnlauzon** [comment]
I have already changed the code to pass a unique nonce during each contract. Closing.

**Comment by ekkis** [comment]
> Transactions submitted even with 1 second interval should be unique since they reference different head blocks (even if all other fields in the transactions are exactly the same).
> Another option is to use the -f option in cleos by including a nonce action in the transaction that will make the tx unique.
> -f,--force-unique force the transaction to be unique. This will consume extra bandwidth.
> Passing a different nonce with each tx will resolve the problem.

@sylvaincormier is there a --force-unique equivalent in eosjs?

**Comment by ekkis** [comment]
> I have already changed the code to pass a unique nonce during each contract. Closing.

how did you do it? was it a matter of adding some field to the `actions[].data` object passed into the `api.transact`?
