### ISSUE TITLE
Error: "Transaction took too long" when trying to retrieve balance

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/ledger#32]
I receive the following error when I attempt to call `contract.getblnc`:

```
     Error: the string "{\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3080006,\"name\":\"deadline_exception\",\"what\":\"Transaction took too long\",\"details\":[{\"message\":\"deadline exceeded\",\"file\":\"transaction_context.cpp\",\"line_number\":297,\"method\":\"checktime\"},{\"message\":\"pending console output: \",\"file\":\"apply_context.cpp\",\"line_number\":61,\"method\":\"exec_one\"}]}}" was thrown, throw an Error :)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

When I turn on verbose, I get this info:

```
api > post       http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-09-11T15:41:32","ref_block_num":19897,"ref_block_prefix":599977697,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"vtxledger","name":"getblnc","authorization":[{"actor":"vtxledger","permission":"active"}],"data":"08767478747275737435454f5335764271693859537a4643655476347765525477427a566b47435935504e35486d314770333133336d3867394d7448546257"}],"transaction_extensions":[]},"signatures":["SIG_K1_KXMWppEnfVmYty7QdiuszN8mg2ZqwwwRAymYy5VSbmKBFLzhLHSgiu3WHGCXZP7WVLneAhoMTXtQhNRBbvUzzBFEA5sHuC"]}
api < error      { message: 'deadline exceeded',
  file: 'transaction_context.cpp',
  line_number: 297,
  method: 'checktime' } http://ec2-35-183-119-153.ca-central-1.compute.amazonaws.com:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-09-11T15:41:32","ref_block_num":19897,"ref_block_prefix":599977697,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"vtxledger","name":"getblnc","authorization":[{"actor":"vtxledger","permission":"active"}],"data":"08767478747275737435454f5335764271693859537a4643655476347765525477427a566b47435935504e35486d314770333133336d3867394d7448546257"}],"transaction_extensions":[]},"signatures":["SIG_K1_KXMWppEnfVmYty7QdiuszN8mg2ZqwwwRAymYy5VSbmKBFLzhLHSgiu3WHGCXZP7WVLneAhoMTXtQhNRBbvUzzBFEA5sHuC"]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3080006,"name":"deadline_exception","what":"Transaction took too long","details":[{"message":"deadline exceeded","file":"transaction_context.cpp","line_number":297,"method":"checktime"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":61,"method":"exec_one"}]}}
    at /Users/shawn/Development/github/ledger-js/node_modules/eosjs-api/lib/apigen.js:112:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3080006,"name":"deadline_exception","what":"Transaction took too long","details":[{"message":"deadline exceeded","file":"transaction_context.cpp","line_number":297,"method":"checktime"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":61,"method":"exec_one"}]}}', transaction '2ce2975bb94de1eec22300000000010000b88a25157bde00000000cd78b262010000b88a25157bde00000000a8ed32323f08767478747275737435454f5335764271693859537a4643655476347765525477427a566b47435935504e35486d314770333133336d3867394d744854625700'
{"code":500,"message":"Internal Service Error","error":{"code":3080006,"name":"deadline_exception","what":"Transaction took too long","details":[{"message":"deadline exceeded","file":"transaction_context.cpp","line_number":297,"method":"checktime"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":61,"method":"exec_one"}]}}
undefined
```

This happens every time, regardless of whether verbose is on or not.

**Comment by shawnlauzon** [comment]
After restarting the blockchain, this problem was resolved.
